minor: use repeat() instead of repeat_n()
The latter is probably too new and it caused the following issue
with `shuttle deploy`:

    error[E0658]: use of unstable library feature 'iter_repeat_n'